-- Deploy pg_sqitch_example:grants to pg

BEGIN;

-- alpha_master
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA alpha TO alpha_master;
ALTER DEFAULT PRIVILEGES IN SCHEMA alpha GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO alpha_master;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA alpha TO alpha_master;
ALTER DEFAULT PRIVILEGES IN SCHEMA alpha GRANT USAGE ON SEQUENCES TO alpha_master;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA alpha TO alpha_master;
GRANT USAGE, CREATE ON SCHEMA alpha TO alpha_master;

-- beta_master
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA beta TO beta_master;
ALTER DEFAULT PRIVILEGES IN SCHEMA beta GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO beta_master;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA beta TO beta_master;
ALTER DEFAULT PRIVILEGES IN SCHEMA beta GRANT USAGE ON SEQUENCES TO beta_master;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA beta TO beta_master;
GRANT USAGE, CREATE ON SCHEMA beta TO beta_master;

COMMIT;
