-- Revert pg_sqitch_example:grants from pg

BEGIN;

-- alpha_master
REVOKE SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA alpha FROM alpha_master;
ALTER DEFAULT PRIVILEGES IN SCHEMA alpha REVOKE SELECT, INSERT, UPDATE, DELETE ON TABLES FROM alpha_master;
REVOKE USAGE ON ALL SEQUENCES IN SCHEMA alpha FROM alpha_master;
ALTER DEFAULT PRIVILEGES IN SCHEMA alpha REVOKE USAGE ON SEQUENCES FROM alpha_master;
REVOKE EXECUTE ON ALL FUNCTIONS IN SCHEMA alpha FROM alpha_master;
REVOKE USAGE, CREATE ON SCHEMA alpha FROM alpha_master;

-- beta_master
REVOKE SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA beta FROM beta_master;
ALTER DEFAULT PRIVILEGES IN SCHEMA beta REVOKE SELECT, INSERT, UPDATE, DELETE ON TABLES FROM beta_master;
REVOKE USAGE ON ALL SEQUENCES IN SCHEMA beta FROM beta_master;
ALTER DEFAULT PRIVILEGES IN SCHEMA beta REVOKE USAGE ON SEQUENCES FROM beta_master;
REVOKE EXECUTE ON ALL FUNCTIONS IN SCHEMA beta FROM beta_master;
REVOKE USAGE, CREATE ON SCHEMA beta FROM beta_master;

COMMIT;
